name: Terraform CD for Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="env=dev"

      - name: Terraform Apply
        run: terraform apply -auto-approve
