name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: /usr/bin/terraform init

      - name: Terraform Format
        run: /usr/bin/terraform fmt -check

      - name: Terraform Validate
        run: /usr/bin/terraform validate

      - name: Terraform Plan
        run: /usr/bin/terraform plan
